---
#################################
# GitHub Dependabot Config info #
#################################
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"

  # Maintain dependencies for python with pip
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
